name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t longbuibao/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true longbuibao/react-test npm test
 
      - run: docker build -t longbuibao/multi-client-10-14 ./client
      - run: docker build -t longbuibao/multi-nginx-10-14 ./nginx
      - run: docker build -t longbuibao/multi-server-10-14 ./server
      - run: docker build -t longbuibao/multi-worker-10-14 ./worker
 
      - run: docker push longbuibao/multi-client-10-14
      - run: docker push longbuibao/multi-nginx-10-14
      - run: docker push longbuibao/multi-server-10-14
      - run: docker push longbuibao/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: elasticbeanstalk-us-east-1-858201713588
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip