name: Deploy MultiDocker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Building Images
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t longbuibao/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true longbuibao/react-test npm test
 
      - run: docker build -t longbuibao/multi-client-10-14 ./client
      - run: docker build -t longbuibao/multi-nginx-10-14 ./nginx
      - run: docker build -t longbuibao/multi-server-10-14 ./server
      - run: docker build -t longbuibao/multi-worker-10-14 ./worker
 
      - run: docker push longbuibao/multi-client-10-14
      - run: docker push longbuibao/multi-nginx-10-14
      - run: docker push longbuibao/multi-server-10-14
      - run: docker push longbuibao/multi-worker-10-14
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate deployment package
      - uses: actions/checkout
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
      - uses: actions/checkout
      - uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: complex-docker
          environment_name: Complexdocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-858201713588
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip